#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

hours=0
minutes=1
while [ "$hours" -le 12 ]
do
	while [ "$minutes" -le 59 ]
	do
		 if [ "$minutes" -lt 10 ]; then
			echo "$hours:0$minutes"
		fi
		(( minutes++ ))
	done
	(( hours++ ))
	minures=0
done | head -n 70
